### PR TITLE
Mpuncel/unschedule pod client function

### PR DESCRIPTION
**Pull request by mpuncel**

### CODE REVIEW

**Comment by mpuncel** [comment]
sequential after #784

**Comment by rudle** [comment]
I found this chain of PRs pretty tricky to review, but I can't see anything obviously wrong with it. The additive changes here are fairly straightforward and seem to wrap consul operations in a gRPC layer with some opinions about error handling.

:ship:

**Comment by mpuncel** [comment]
I'm going to merge this PR and close 780-784 which just have the commits that are already in this PR. Thanks for reviewing @rudle !

**Comment by petertseng** [comment]
Hello, I am also 👍  on this.

**Pull request merged**
