### PR TITLE
add before_launch hook type

### PR DESCRIPTION
**Pull request by anthonybishopric**
Some actions must be taken after we have turned off the old version of the app

### CODE REVIEW

**Comment by petertseng** [comment]
OK, seems good to me. Will it be necessary to add this to the switch/case in `RunHookType` in `orchestrate_test` ? Guess it's not strictly necessary, since we don't test each particular hook type, but perhaps for uniformity...?

**Comment by anthonybishopric** [comment]
Sure, I can do that

**Comment by bwester** [comment]
I'm glad you added extra comments describing the differences between the hooks; it's quite non-intuitive.  That said, it's so non-intuitive that it makes me question my beliefs about when _any_ of those hooks get run.

These hooks have become complex enough that it's time for a formal state diagram to explain them.

**Comment by anthonybishopric** [comment]
@bwester agreed, I can start working on that in a bit.

**Pull request merged**
