### PR TITLE
Handle return values in p2-exec before checking errno

### PR DESCRIPTION
**Pull request by tummychow**
plus various refactors. Thanks @syamp. cc @anthonybishopric @eam

### CODE REVIEW

**Comment by anthonybishopric** [comment]
:+1:

**Comment by syamp** [comment]
You want to check ret value first and then in the sub block retrieve err if present.

**Comment by anthonybishopric** [comment]
@syamp how is that different from short circuiting the `ret !=0` part of the if statement?

**Comment by anthonybishopric** [comment]
oh i suppose `ret` may be `!= 0` but error could be nil, in which case this would falsely say it was successful

**Comment by syamp** [comment]
The idea is not bother about checking for errno unless return value is not as expected.  return
value should be your only signal. In this particular case, it might not matter but is a wrong pattern imo.

From manpage of errno:
----
 Its value is significant only
       when the return value of the call indicated an error (i.e., -1 from
       most system calls; -1 or NULL from most library functions); a
       function that succeeds is allowed to change errno.

**Pull request merged**
