### PR TITLE
log the time spent processing RC updates as a string instead of nanos…

### PR DESCRIPTION
**Pull request by mpuncel**
…econd integer

### CODE REVIEW

**Comment by rudle** [comment]
:+1: looks like it works to me. How did you test this?

**Comment by mpuncel** [comment]
just by running an equivalent on play: http://play.golang.org/p/5odM22XwUA

**Comment by mpuncel** [comment]
although maybe integers are easier to do math on

**Comment by rudle** [comment]
I think it's fine as is. We definitely want some units in the output and the quantities should be small enough to allow mental arithmetic.

**Pull request merged**
