### PR TITLE
Labels

### PR DESCRIPTION
**Pull request by tummychow**
Big diff due to kubernetes packages. This adds basic support for attaching labels to pods or nodes in consul. The API is not exercised anywhere right now. The labels for an object are stored as a single JSON document under `/labels/node/<nodename>` and `/labels/pod/<podname>`. We'll still have to decide what exactly a "pod name" is in this context, but slash-separated strings will probably work.

### CODE REVIEW

**Comment by tummychow** [comment]
ugh, CI failure because a linux-only dependency wasn't `godep save`d. will fix shortly

**Comment by tummychow** [comment]
- merged linux-only dependencies into first commit to avoid horrible ugly giant diffs
- changed `POD` and `NODE` to be constants
- used enums for label operators instead of strings

will implement auto retry logic shortly plus tests

**Comment by tummychow** [comment]
- implemented optional auto-retry after CAS failure
- merged all implementation commits into one

**Comment by anthonybishopric** [comment]
I think I'm satisfied :+1:

**Comment by tummychow** [comment]
- removed redundant nil check in convertkvptolabeled

**Comment by tummychow** [comment]
- added type argument to GetMatches

**Comment by petertseng** [comment]
Yup :+1:

**Pull request merged**
