### PR TITLE
Add ability to fetch from Google Storage

### PR DESCRIPTION
**Pull request by drcapulet**
Wasn't sure of a great way to test this, could potentially cache the result of either of the calls to `google.DefaultClient` or `storage.New(client)` and inject that as part of testing?

### CODE REVIEW

**Comment by anthonybishopric** [comment]
BasicFetcher should probably have a google `Client` and that should be provided by the test. The default fetcher can just use `google.DefaultClient`.

**Comment by mpuncel** [comment]
@drcapulet you can extract the critical section to a function and do a `defer f.mu.Unlock()` immediately after locking it

**Comment by anthonybishopric** [comment]
@drcapulet @mpuncel can we just do this in `init()` for that file, just for the default instance? We don't need to introduce all the mutex logic that way.

**Comment by mpuncel** [comment]
yeah that works

**Comment by mpuncel** [comment]
alternatively we could use `sync.Once`

**Comment by anthonybishopric** [comment]
If it's not necessary to introduce concurrency primitives I'd like to avoid it altogether.

**Comment by drcapulet** [comment]
Updated & added a test. However, the call to `google.DefaultClient` will fail for people w/o the Google config setup (somehow it passes on Travis and was passing locally since I'm correctly setup).

I'm thinking about moving this into another file so that you can enable this feature at compile time via a build tag, thoughts?

**Comment by anthonybishopric** [comment]
I'd like to leave this as is, for now.

**Comment by anthonybishopric** [comment]
🚢

**Comment by drcapulet** [comment]
Ping, everything look good? I don't have merge access.

**Comment by drcapulet** [comment]
Updated since I noticed `artifact_verifier.go` also had a list of protocols.

**Comment by drcapulet** [comment]
Ping @anthonybishopric, this look good?

**Comment by rudle** [comment]
Is PR still desirable? Please close if not.

**Comment by rudle** [comment]
Sorry, but this PR must be closed because it is stale.

**Comment by drcapulet** [comment]
Desirable but probably better implemented as an artifact repository.

**Pull request closed without merging**
