### PR TITLE
Use SHA256 in pod manifests

### PR DESCRIPTION
**Pull request by tummychow**
as we mentioned before

### CODE REVIEW

**Comment by petertseng** [comment]
Cool. with `git grep sha` I think we may like to change `bin/p2-inspect/README.md` ? Otherwise I think everything else is covered.

**Comment by tummychow** [comment]
Good catch, I'll make those shas in the readme 64chars long.

**Comment by petertseng** [comment]
:+1:

**Comment by anthonybishopric** [comment]
:+1:

**Pull request merged**
