### PR TITLE
Move post-activate output to logrus field

### PR DESCRIPTION
**Pull request by tummychow**
This shouldn't be in the logrus message in the first place; parametric data should be in fields.

### CODE REVIEW

**Comment by tummychow** [comment]
test failure is flake - probably failed to connect to the server and the response was nil or malformed. Will fix tomorrow

**Comment by rudle** [comment]
:+1:

**Comment by mpuncel** [comment]
:+1:

**Comment by tummychow** [comment]
fixed flake

**Comment by petertseng** [comment]
yup :+1:

**Pull request merged**
