### PR TITLE
Fix bugs in callers of WatchPods()

### PR DESCRIPTION
**Pull request by mpuncel**
communicate an empty []ManifestResult

### CODE REVIEW

**Comment by bwester** [comment]
super nit: Please use [standard](https://github.com/blog/926-shiny-new-commit-styles) [git](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) [formatting](http://chris.beams.io/posts/git-commit/) in your commit message, and take the opportunity to [explain why](https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message) your diff does what it does.

**Comment by bwester** [comment]
In isolation, it seems like highly desirable behavior that if a caller wants to watch an object for changes, it get notified when the object is deleted.  Why do we want to mask this?

**Comment by mpuncel** [comment]
I was restoring the behavior of `WatchPods()` prior to https://github.com/square/p2/pull/248/files. It is useful to be notified of deletions though like you said, i'll look at changing consumers of this function to properly handle an empty result slice.

**Comment by mpuncel** [comment]
@petertseng I'm not even sure how to handle the situation where length > 1. Which manifest would I use if there is more than one? bubble up an error and block for probably forever?

**Comment by tummychow** [comment]
yeah let's log something if the length is greater than 1, other than that looks fine

**Comment by mpuncel** [comment]
will merge once green

**Comment by bwester** [comment]
:+1:

**Pull request merged**
