### PR TITLE
Make the roll farm robust to RUs with missing RCs.

### PR DESCRIPTION
**Pull request by mpuncel**
If a rolling update exists in consul and is missing either its new or
old RC, the rolling update cannot be handled because the enable/disable
step at the beginning of the roll handler will fail.

This commit validates that both RCs in an RU exist before attempting to
run it. If one of the RCs is missing, the RU is deleted.

### CODE REVIEW

**Comment by mpuncel** [comment]
Open question: If the old RC is missing, should this also validate that the new RC is enabled and if not, enable it?

**Comment by mpuncel** [comment]
an alternative to this approach would be to push this logic into the up

**Comment by mpuncel** [comment]
rebased on master

**Comment by bwester** [comment]
This looks fine to me. 🚢

**Pull request merged**
