### PR TITLE
Mpuncel/rework artifact verifier interfaces

### PR DESCRIPTION
**Pull request by mpuncel**

### CODE REVIEW

**Comment by petertseng** [comment]
wip commit sighted!

**Comment by mpuncel** [comment]
you're too fast @petertseng

**Comment by mpuncel** [comment]
hmm there might be some commits in here i don't need

**Comment by mpuncel** [comment]
note to reviewers: review https://github.com/square/p2/pull/534 first, this has some commits from there

**Comment by mpuncel** [comment]
declining because i have a better alternative to this PR

**Pull request closed without merging**
