### PR TITLE
Mpuncel/unschedule pod

### PR DESCRIPTION
**Pull request by mpuncel**

### CODE REVIEW

**Comment by rudle** [comment]
Have you thought about retries for this? It would be nice if I could call this repeatedly without encountering an error.

**Comment by mpuncel** [comment]
I was thinking clients could check for the NotFound status. in some cases that be a "whoops i gave you the wrong uuid" and in others it might be "i know the uuid is right, don't care if it was there just want to make sure it's gone"

**Comment by mpuncel** [comment]
should be easy to check with `if grpc.Code(err) == codes.NotFound`

**Comment by rudle** [comment]
neat! :ship:

**Pull request merged**
