### PR TITLE
Use testdata for test data

### PR DESCRIPTION
**Pull request by rudle**
Primary desire is to have godep ignore these files in projects that pull
in p2/pkg/...

https://github.com/tools/godep/issues/140

### CODE REVIEW

**Comment by petertseng** [comment]
While you're at it, would you like to also move some others?

```$ find . -name "*.tar.*"
./artifact/myapp_123.tar.gz
./auth/test_artifact/hello-server_3881c78ed47ae8be4a4080178f2d46cc174a5a95.tar.gz
./auth/test_artifact/hello-server_3881c78ed47ae8be4a4080178f2d46cc174a5a95.tar.gz.manifest
./auth/test_artifact/hello-server_3881c78ed47ae8be4a4080178f2d46cc174a5a95.tar.gz.manifest.sig
./auth/test_artifact/hello-server_3881c78ed47ae8be4a4080178f2d46cc174a5a95.tar.gz.manifest.sig.raw
./auth/test_artifact/hello-server_3881c78ed47ae8be4a4080178f2d46cc174a5a95.tar.gz.sig
./gzip/file_with_selflink.tar.gz
./gzip/file_without_dir.tar.gz
./gzip/path_with_parent.tar.gz
./pods/hoisted-hello_3c021aff048ca8117593f9c71e03b87cf72fd440.tar.gz
./preparer/hoisted-hello_def456.tar.gz
```

**Comment by rudle** [comment]
You're right to request a cohesive change. I'll pick this PR up and do a more thorough sweep when time permits.

**Comment by bwester** [comment]
I'm all for the change. I'm curious, what prompted this?  The motivation in the discussion you linked to was that "testdata" folders could contain invalid Go source files. That doesn't apply here.

**Comment by rudle** [comment]
A recent `godep update` in Square's code introduced a binary file in a diff. That's undesirable.

**Comment by mpuncel** [comment]
👍

**Comment by rudle** [comment]
I updated this PR to capture the other instances in `pkg/`. PTAL

**Comment by mpuncel** [comment]
lgtm

**Pull request merged**
