### PR TITLE
errcheck the repo

### PR DESCRIPTION
**Pull request by rudle**
This list populated by `errcheck -ignoretests github.com/square/p2/pkg/... | grep -v defer`

I ignored defer cases because they are tricky to get right. I also wanted to get this merged ASAP as I caught a few pretty scary ignored errors!

Some discussion on err handling in defer can be found here: https://github.com/kisielk/errcheck/issues/55, https://github.com/kisielk/errcheck/issues/77

### CODE REVIEW

**Comment by rudle** [comment]
Still need to reason about how to get this into travis given that the exit code from

**Comment by anthonybishopric** [comment]
👍  yesss

**Comment by mpuncel** [comment]
👍

**Comment by rudle** [comment]
PTAL travis is now wired up and verified working. By working I mean that the build will fail if someone introduces an unchecked error.

**Comment by mpuncel** [comment]
👍

**Pull request merged**
